spring:
  application:
    name: spring-boot-jwt
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_jwt
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret-key: 061af0d866579af420482ef16cf2955e0a342b0c4edb7799e28de34b61183365
